### ISSUE TITLE
Please add the Insert Picture ...

### ISSUE THREAD

**Issue by eArabic** [phhpro/atomchat#3] opened 2018-01-03 06:12 UTC
Hello dear friend
Thank you very much, it's a great script that works excellently
Please add the Insert Picture or File feature that is important

**Comment by phhpro** [comment] 2018-01-03 15:17
Hello again.

The same answer applies here as given to your identical request for the PHP Easy Comments script. I'll get back to you if ever such feature becomes available.

**Comment by eArabic** [comment] 2018-01-03 17:06
Thank you so much my dear friend
Always my goal is to learn and learn how to add features and learn php code

**Comment by phhpro** [comment] 2018-01-03 17:29
Keep at it. The web is constantly evolving and PHP is no exception. I keep falling from one hole into another myself trying to keep my sources up-to-date. Usually it works, but I do have my moments :) I'll be closing this ticket now but feel free to contact me per mail (see @author tag) if you need help with general webdesign or coding. Regards.

**Comment by eArabic** [comment] 2018-01-04 12:53
Thank you so much my dear friend
Do you advise me to continue learning php or learn another programming language?

**Comment by phhpro** [comment] 2018-01-04 21:02
Please use email for off-topic questions. But since I'm here anyway, the answer would rather depend on what's your focus. If at some point you want to write your own PHP scripts than you'd be well advised to read up the docs along with some try and error.

There are plenty of languages for offline and online, or both, and each has its particular charms, though I believe the web is mainly build on PHP. I haven't used Perl for ages and never really considered Python. That's better suited for local desktop apps, though one or two sites are probably running Python stuff.

When it comes to desktop I still prefer C++ or vanilla C, but that's likely due to the nature of the stuff I write. No any one single language is best in class for everything. One has to wage the pro's and con's, how efficient the sources versus how fast the app, versus foobar, etc.

OK, I'll be having another cuppa and zap around a little before hitting the pillows. Busy day today and more fun ahead tomorrow. Last weekend before I'm flying out Monday night. Anything else please use mail, thanks.

**Comment by phhpro** [comment] 2018-04-21 17:41
Hi, just posted over at the PHP Easy Comments branch. Anyway, in case you missed it, the upload feature has arrived. Feedback welcome, thanks.

**Comment by eArabic** [comment] 2018-04-23 07:17
Hello dear friend
Thank you very much for the wonderful new update, I did the test did not work I noticed that the file path is different, how to modify the path of files it opens on this file:
**http://www.example.com/atom/user-content/if_go-home_118770.png**
My real path is:
**http://www.example.com/Pro/chat/atom/user-content/if_go-home_118770.png**

From where to adjust the path of image files, and thank you very much for this wonderful update is useful during the communication of others and conversation.

**Comment by phhpro** [comment] 2018-04-23 10:08
Not sure if I follow. The script auto-detects the directory in which it is installed and then appends user-content to store uploads. If the script is in /foo/bar/atomchat it will use /foo/bar/atomchat/user-content. If it was in /bar/baz/very/deep/path/to/script then it would save uploads in /bar/baz/very/deep/path/to/script/user-content. Please post back the proper URL where you have the script installed and I'll try to reproduce. You don't have any redirects configured, do you?

**Comment by phhpro** [comment] 2018-04-23 13:36
OK, just pushed a minor update. Default language on line #68 `$lang_def = "en";` Change to `$lang_def = "ar";` to use Arabic language file. Upload folder on line #104 `$up_fold = "user-content";` Refer to notes above the setting. HTH

**Comment by eArabic** [comment] 2018-04-24 10:05
Dear Friend
Thank you very much, I could not make it work, sorry for the many questions, I tried not working for me.
This address:
http://bok.altervista.org/Pro/Chat/atomchat/index.php

echo $_SERVER["DOCUMENT_ROOT"] = /var/www/html

**Comment by phhpro** [comment] 2018-04-24 10:32
First, there's definitely a redirect of sorts because bok.altervista.org immediately opens bok.altervista.org/easy-comments/ Posting text works OK, but uploads are broken, though the correct URL is there. I find it odd that an almost identical function works in Easy Comments but not in Atomchat. Both scripts are on the same host, are they?

Check where that redirect sits and take it out while testing. It's no help fixing what's not broken. You should probably just drop the script in / to check if the redirect kicks in or not. The deeper you stack the path, the more chances to import errors along the way.

Regarding path, I would have though we had that solved. Your env is broken in as much that the $_SERVER global returns Apache's default server path instead your actual user path; a common nuisance on free hosters. This effectively means you'll need to hard-code the full path wherever a script makes a reference to it.

Never mind asking. I'm doing that an awful lot myself. That's how you learn things.

**Comment by phhpro** [comment] 2018-04-24 11:25
I might just have found a way around. Please fetch the updated chat.php and try again. Post back if it fixes the upload issue.

**Comment by eArabic** [comment] 2018-04-24 18:06
Dear Friend
Thank you very much, thank you very much now for fully functioning.
Thank you very much and appreciation for your help
[Link Web]( http://bok.altervista.org/Pro/Chat/atomchat/index.php
)

![ee](https://user-images.githubusercontent.com/24383546/39205388-2524872c-4803-11e8-83c9-37646d6e21e7.png)

**Comment by phhpro** [comment] 2018-04-24 18:25
Yep. Just checked and posted a snippet to verify.  Don't forget to adjust the maximum upload size if your host has a filesize limit less <2 MiB. Thanks for the feedback.

**Closed** 2018-07-20 10:10 UTC
