### ISSUE TITLE
Refresh: Can't Set Name

### ISSUE THREAD

**Issue by Mixddux** [phhpro/atomchat#2] opened 2017-09-02 16:45 UTC
Me again. 

Seems there's a refresh that clears my registration data. I.E.I can't create a name because it keeps refreshing. 

And there are two 'name' instances.

http://mixdd.com/atomchat/atomchat-master/

**Comment by phhpro** [comment] 2017-09-03 09:48
Yeah, seems to be caused by the stylesheet not getting read. Should be fixed in 20170903. Please try again. Sorry, and thanks for bearing with me :)

**Comment by Mixddux** [comment] 2017-09-05 19:04
No problem. I'd like to see this work. I'm hoping to create a UI for the fun on it. =)

**Comment by Mixddux** [comment] 2017-09-05 19:14
It seems to be working for me. Yay! 

The blinking is a bit annoying, but I get it. You may want to default to the 'white' them. IF I can find some friends, I'll will test it out with them.

Thank you!

**Comment by phhpro** [comment] 2017-09-06 08:47
Glad to hear you've had success, after all. I've put up a live demo for the time being. Fixing the trim part screwed something else, which I only found by chance after flushing the caches. Looks OK again. If you'd like to compare, it's at phclaus.com/demo/atomchat/

P.S. Blinking? The original default was the grey theme but plain white has its charms.

**Closed** 2017-09-06 14:52 UTC

**Comment by Mixddux** [comment] 2017-12-20 20:05
Oh no, sorry man, it's been a while!

**Comment by phhpro** [comment] 2017-12-20 20:25
Yep. In case you care to give it another try and need someone on the other side of the screen let me know. Though my present TZ is GMT+1 I usually don't have much of a problem coordinating differing offsets. Reagrds.
